### ISSUE TITLE
Fix Resource Download Error

### ISSUE THREAD

**Issue by escudeler** [Leandro2905/Shiginima-Launcher#1]
O endereço para Download de resources, passou a requerer https;

Fix se dá na linha 25 do arquivo de constantes LauncherConstants.java e/ou linha 319 da classe MinecraftVersionManager.java

Obrigado =D

------------------------------------------------------------------------------------------------
English version:

The address for downloading resources now requires https;
Fix is on line 25 of the LauncherConstants.java constants file and/or line 319 of class MinecraftVersionManager.java

Thank you =D

**Comment by V4nnura** [comment]
Obrigado, Feito! / Thanks, Done!

> O endereço para Download de resources, passou a requerer https;
> 
> Fix se dá na linha 25 do arquivo de constantes LauncherConstants.java e/ou linha 319 da classe MinecraftVersionManager.java
> 
> Obrigado =D
> 
> English version:
> 
> The address for downloading resources now requires https; Fix is on line 25 of the LauncherConstants.java constants file and/or line 319 of class MinecraftVersionManager.java
> 
> Thank you =D
